[package]
name = "rocket-benchmarks"
version = "0.0.0"
edition = "2018"
publish = false

[workspace]

[[bench]]
name = "main"
path = "src/bench.rs"
harness = false

[dev-dependencies]
rocket = { path = "../core/lib/" }
criterion = { version = "0.3", features = ["html_reports"] }
